"""phase_31_fix_missing_column_comments

Revision ID: 27d9dc5d2b31
Revises: d2d2e3f4a5b6
Create Date: 2026-07-21 18:57:35.550503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27d9dc5d2b31'
down_revision: Union[str, None] = 'd2d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_call_traces', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_call_traces', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('anchor_schedules', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('anchor_schedules', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('compliance_rules', 'rule_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60),
               comment='稳定规则编码',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               comment='规则名称',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               comment='食品宣传/经营承诺/绝对化/站外导流/资质证明',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'pattern',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='需要人工复核的关键词，使用竖线分隔',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'severity',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='warning/critical',
               existing_nullable=False,
               existing_server_default=sa.text("'warning'"))
    op.alter_column('compliance_rules', 'guidance',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='合规改写或核验建议',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'source_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               comment='公开规则来源',
               existing_nullable=True)
    op.alter_column('compliance_rules', 'version',
               existing_type=mysql.INTEGER(),
               comment='规则版本',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('compliance_rules', 'enabled',
               existing_type=mysql.INTEGER(),
               comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('review_action_items', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='整改标题',
               existing_nullable=False)
    op.alter_column('review_action_items', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='整改要求',
               existing_nullable=True)
    op.alter_column('review_action_items', 'owner_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='负责人',
               existing_nullable=True)
    op.alter_column('review_action_items', 'priority',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='low/medium/high',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('review_action_items', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='pending/in_progress/completed/verified',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('review_action_items', 'due_at',
               existing_type=mysql.DATETIME(),
               comment='计划完成时间',
               existing_nullable=True)
    op.alter_column('review_action_items', 'verification_session_id',
               existing_type=mysql.INTEGER(),
               comment='验证场次ID',
               existing_nullable=True)
    op.alter_column('review_action_items', 'verification_note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='验证结论',
               existing_nullable=True)
    op.alter_column('review_findings', 'finding_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='observation/opportunity/risk',
               existing_nullable=False,
               existing_server_default=sa.text("'observation'"))
    op.alter_column('review_findings', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               comment='留人/互动/资料钩子/私信留资/内容/合规/数据质量',
               existing_nullable=False)
    op.alter_column('review_findings', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='发现标题',
               existing_nullable=False)
    op.alter_column('review_findings', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='发现说明',
               existing_nullable=True)
    op.alter_column('review_findings', 'severity',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='info/warning/critical',
               existing_nullable=False,
               existing_server_default=sa.text("'info'"))
    op.alter_column('review_findings', 'start_seconds',
               existing_type=mysql.DECIMAL(precision=12, scale=1),
               comment='证据相对开播开始秒数',
               existing_nullable=True)
    op.alter_column('review_findings', 'end_seconds',
               existing_type=mysql.DECIMAL(precision=12, scale=1),
               comment='证据相对开播结束秒数',
               existing_nullable=True)
    op.alter_column('review_findings', 'evidence_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='metric/comment/transcript/session',
               existing_nullable=False)
    op.alter_column('review_findings', 'evidence_text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='真实证据原文或指标变化',
               existing_nullable=True)
    op.alter_column('review_findings', 'metric_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60),
               comment='关联指标名',
               existing_nullable=True)
    op.alter_column('review_findings', 'metric_before',
               existing_type=mysql.DECIMAL(precision=14, scale=4),
               comment='变化前指标',
               existing_nullable=True)
    op.alter_column('review_findings', 'metric_after',
               existing_type=mysql.DECIMAL(precision=14, scale=4),
               comment='变化后指标',
               existing_nullable=True)
    op.alter_column('review_findings', 'confidence',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment='判断置信度0-1',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0000'"))
    op.alter_column('review_findings', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment='rule/ai/manual',
               existing_nullable=False,
               existing_server_default=sa.text("'rule'"))
    op.alter_column('review_findings', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='open/confirmed/dismissed/resolved',
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('script_assets', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               comment='开场留人/选址/预算/品牌/供应链/毛利/损耗/资料钩子/私信承接',
               existing_nullable=False)
    op.alter_column('script_assets', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='话术标题',
               existing_nullable=False)
    op.alter_column('script_assets', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='真实话术原文',
               existing_nullable=False)
    op.alter_column('script_assets', 'start_seconds',
               existing_type=mysql.DECIMAL(precision=12, scale=1),
               comment='片段开始秒数',
               existing_nullable=True)
    op.alter_column('script_assets', 'end_seconds',
               existing_type=mysql.DECIMAL(precision=12, scale=1),
               comment='片段结束秒数',
               existing_nullable=True)
    op.alter_column('script_assets', 'performance_note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='关联真实效果说明',
               existing_nullable=True)
    op.alter_column('script_assets', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='candidate/approved/archived',
               existing_nullable=False,
               existing_server_default=sa.text("'candidate'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('script_assets', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='candidate/approved/archived',
               existing_nullable=False,
               existing_server_default=sa.text("'candidate'"))
    op.alter_column('script_assets', 'performance_note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='关联真实效果说明',
               existing_nullable=True)
    op.alter_column('script_assets', 'end_seconds',
               existing_type=mysql.DECIMAL(precision=12, scale=1),
               comment=None,
               existing_comment='片段结束秒数',
               existing_nullable=True)
    op.alter_column('script_assets', 'start_seconds',
               existing_type=mysql.DECIMAL(precision=12, scale=1),
               comment=None,
               existing_comment='片段开始秒数',
               existing_nullable=True)
    op.alter_column('script_assets', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='真实话术原文',
               existing_nullable=False)
    op.alter_column('script_assets', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='话术标题',
               existing_nullable=False)
    op.alter_column('script_assets', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               comment=None,
               existing_comment='开场留人/选址/预算/品牌/供应链/毛利/损耗/资料钩子/私信承接',
               existing_nullable=False)
    op.alter_column('review_findings', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='open/confirmed/dismissed/resolved',
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('review_findings', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='rule/ai/manual',
               existing_nullable=False,
               existing_server_default=sa.text("'rule'"))
    op.alter_column('review_findings', 'confidence',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment=None,
               existing_comment='判断置信度0-1',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0000'"))
    op.alter_column('review_findings', 'metric_after',
               existing_type=mysql.DECIMAL(precision=14, scale=4),
               comment=None,
               existing_comment='变化后指标',
               existing_nullable=True)
    op.alter_column('review_findings', 'metric_before',
               existing_type=mysql.DECIMAL(precision=14, scale=4),
               comment=None,
               existing_comment='变化前指标',
               existing_nullable=True)
    op.alter_column('review_findings', 'metric_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60),
               comment=None,
               existing_comment='关联指标名',
               existing_nullable=True)
    op.alter_column('review_findings', 'evidence_text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='真实证据原文或指标变化',
               existing_nullable=True)
    op.alter_column('review_findings', 'evidence_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='metric/comment/transcript/session',
               existing_nullable=False)
    op.alter_column('review_findings', 'end_seconds',
               existing_type=mysql.DECIMAL(precision=12, scale=1),
               comment=None,
               existing_comment='证据相对开播结束秒数',
               existing_nullable=True)
    op.alter_column('review_findings', 'start_seconds',
               existing_type=mysql.DECIMAL(precision=12, scale=1),
               comment=None,
               existing_comment='证据相对开播开始秒数',
               existing_nullable=True)
    op.alter_column('review_findings', 'severity',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='info/warning/critical',
               existing_nullable=False,
               existing_server_default=sa.text("'info'"))
    op.alter_column('review_findings', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='发现说明',
               existing_nullable=True)
    op.alter_column('review_findings', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='发现标题',
               existing_nullable=False)
    op.alter_column('review_findings', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               comment=None,
               existing_comment='留人/互动/资料钩子/私信留资/内容/合规/数据质量',
               existing_nullable=False)
    op.alter_column('review_findings', 'finding_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               comment=None,
               existing_comment='observation/opportunity/risk',
               existing_nullable=False,
               existing_server_default=sa.text("'observation'"))
    op.alter_column('review_action_items', 'verification_note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='验证结论',
               existing_nullable=True)
    op.alter_column('review_action_items', 'verification_session_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='验证场次ID',
               existing_nullable=True)
    op.alter_column('review_action_items', 'due_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='计划完成时间',
               existing_nullable=True)
    op.alter_column('review_action_items', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='pending/in_progress/completed/verified',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('review_action_items', 'priority',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='low/medium/high',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('review_action_items', 'owner_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='负责人',
               existing_nullable=True)
    op.alter_column('review_action_items', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='整改要求',
               existing_nullable=True)
    op.alter_column('review_action_items', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='整改标题',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'enabled',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('compliance_rules', 'version',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='规则版本',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('compliance_rules', 'source_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               comment=None,
               existing_comment='公开规则来源',
               existing_nullable=True)
    op.alter_column('compliance_rules', 'guidance',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='合规改写或核验建议',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'severity',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='warning/critical',
               existing_nullable=False,
               existing_server_default=sa.text("'warning'"))
    op.alter_column('compliance_rules', 'pattern',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='需要人工复核的关键词，使用竖线分隔',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               comment=None,
               existing_comment='食品宣传/经营承诺/绝对化/站外导流/资质证明',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               comment=None,
               existing_comment='规则名称',
               existing_nullable=False)
    op.alter_column('compliance_rules', 'rule_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60),
               comment=None,
               existing_comment='稳定规则编码',
               existing_nullable=False)
    op.alter_column('anchor_schedules', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('anchor_schedules', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('ai_call_traces', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_call_traces', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
