"""Phase 1: 创建 10 张核心业务表

Revision ID: 550ffd1c12ac
Revises: 
Create Date: 2026-07-09 22:23:56.710380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550ffd1c12ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='直播间ID'),
    sa.Column('account_name', sa.String(length=100), nullable=False, comment='账号名称'),
    sa.Column('anchor_name', sa.String(length=100), nullable=False, comment='主播名称'),
    sa.Column('douyin_id', sa.String(length=100), nullable=True, comment='抖音号'),
    sa.Column('room_id_str', sa.String(length=100), nullable=True, comment='直播间原始ID'),
    sa.Column('team_name', sa.String(length=100), nullable=True, comment='所属团队/组'),
    sa.Column('platform', sa.String(length=20), nullable=True, comment='平台'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态：1启用 0停用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='场次ID'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='关联直播间ID'),
    sa.Column('session_title', sa.String(length=200), nullable=True, comment='直播场次标题/名称'),
    sa.Column('dashboard_url', sa.String(length=1000), nullable=True, comment='直播大屏页面URL'),
    sa.Column('stream_url', sa.String(length=2000), nullable=True, comment='直播流m3u8地址'),
    sa.Column('live_start_time', sa.DateTime(), nullable=True, comment='开播时间'),
    sa.Column('live_end_time', sa.DateTime(), nullable=True, comment='下播时间'),
    sa.Column('live_duration_seconds', sa.Integer(), nullable=True, comment='直播时长（秒）'),
    sa.Column('live_status', sa.String(length=20), nullable=True, comment='直播状态：liveing/ended'),
    sa.Column('total_viewers', sa.Integer(), nullable=True, comment='累计观看人数'),
    sa.Column('avg_watch_seconds', sa.DECIMAL(precision=10, scale=1), nullable=True, comment='人均观看时长（秒）'),
    sa.Column('peak_online_count', sa.Integer(), nullable=True, comment='最高在线人数'),
    sa.Column('realtime_online_count', sa.Integer(), nullable=True, comment='实时在线人数'),
    sa.Column('private_message_count', sa.Integer(), nullable=True, comment='私信人数'),
    sa.Column('scene_leads_count', sa.Integer(), nullable=True, comment='全场景线索人数'),
    sa.Column('ad_cost', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='广告消耗（元）'),
    sa.Column('mini_windmill_click_count', sa.Integer(), nullable=True, comment='小风车点击次数'),
    sa.Column('new_followers', sa.Integer(), nullable=True, comment='涨粉量'),
    sa.Column('exposure_enter_rate', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='曝光进入率'),
    sa.Column('share_rate', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='分享率'),
    sa.Column('like_rate', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='点赞率'),
    sa.Column('comment_rate', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='评论率'),
    sa.Column('interaction_rate', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='互动率'),
    sa.Column('comments_count', sa.Integer(), nullable=True, comment='评论总数'),
    sa.Column('leads_count', sa.Integer(), nullable=True, comment='留资总数'),
    sa.Column('natural_traffic_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='自然流量占比'),
    sa.Column('marketing_traffic_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='营销流量占比'),
    sa.Column('other_traffic_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='其他流量占比'),
    sa.Column('live_exposure_users', sa.Integer(), nullable=True, comment='直播间曝光人数'),
    sa.Column('live_enter_users', sa.Integer(), nullable=True, comment='直播进入人数'),
    sa.Column('card_click_users', sa.Integer(), nullable=True, comment='小风车/讲解卡点击人数'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['room_id'], ['live_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联直播场次ID'),
    sa.Column('report_type', sa.String(length=30), nullable=False, comment='类型：speech_score/trend/anomaly/optimization'),
    sa.Column('report_title', sa.String(length=200), nullable=True, comment='报告标题'),
    sa.Column('report_content', sa.JSON(), nullable=True, comment='报告内容（JSON格式）'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联直播场次ID'),
    sa.Column('user_nickname', sa.String(length=100), nullable=True, comment='用户昵称'),
    sa.Column('comment_content', sa.Text(), nullable=True, comment='评论内容'),
    sa.Column('comment_time', sa.DateTime(), nullable=True, comment='评论时间'),
    sa.Column('is_high_intent', sa.Integer(), nullable=True, comment='是否高意向：1是 0否'),
    sa.Column('sentiment', sa.String(length=20), nullable=True, comment='情绪倾向：positive/neutral/negative'),
    sa.Column('keywords', sa.String(length=500), nullable=True, comment='关键词（逗号分隔）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='关联直播场次ID'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类：优质话术/分析结论/优化案例'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('source_type', sa.String(length=30), nullable=True, comment='来源：ai_analysis/manual/transcript'),
    sa.Column('embedding_json', sa.Text(), nullable=True, comment='预留给向量检索的 embedding 数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联直播场次ID'),
    sa.Column('lead_name', sa.String(length=100), nullable=True, comment='留资姓名'),
    sa.Column('lead_phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('lead_source', sa.String(length=50), nullable=True, comment='来源：私信/小风车/表单/评论'),
    sa.Column('is_valid', sa.Integer(), nullable=True, comment='是否有效留资：1有效 0无效'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='留资时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_audience_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联直播场次ID'),
    sa.Column('dimension_type', sa.String(length=20), nullable=False, comment='维度类型：age/gender/region/province/city'),
    sa.Column('dimension_name', sa.String(length=50), nullable=False, comment='维度名称，如31-40岁/男/广东'),
    sa.Column('ratio', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='占比'),
    sa.Column('count', sa.Integer(), nullable=True, comment='人数'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联直播场次ID'),
    sa.Column('metric_time', sa.DateTime(), nullable=False, comment='指标采集时间'),
    sa.Column('exposure_count', sa.Integer(), nullable=True, comment='曝光次数'),
    sa.Column('online_count', sa.Integer(), nullable=True, comment='在线人数'),
    sa.Column('enter_count', sa.Integer(), nullable=True, comment='进入人数'),
    sa.Column('enter_fans_count', sa.Integer(), nullable=True, comment='进入粉丝数'),
    sa.Column('leave_count', sa.Integer(), nullable=True, comment='离开人数'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞量'),
    sa.Column('comment_count', sa.Integer(), nullable=True, comment='评论量'),
    sa.Column('follow_count', sa.Integer(), nullable=True, comment='关注次数'),
    sa.Column('natural_traffic_count', sa.Integer(), nullable=True, comment='自然流量数'),
    sa.Column('marketing_traffic_count', sa.Integer(), nullable=True, comment='营销流量数'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_metric_time', 'live_metrics', ['session_id', 'metric_time'], unique=False)
    op.create_table('transcript_full_texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联直播场次ID'),
    sa.Column('full_text', sa.Text(), nullable=True, comment='完整拼接话术'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联直播场次ID'),
    sa.Column('segment_start', sa.DECIMAL(precision=10, scale=1), nullable=True, comment='片段开始时间（秒）'),
    sa.Column('segment_end', sa.DECIMAL(precision=10, scale=1), nullable=True, comment='片段结束时间（秒）'),
    sa.Column('text_content', sa.Text(), nullable=True, comment='话术内容'),
    sa.Column('segment_type', sa.String(length=50), nullable=True, comment='话术类型：开场/产品介绍/互动/留资引导/结束'),
    sa.Column('asr_status', sa.String(length=20), nullable=True, comment='转写状态：pending/processing/completed/failed'),
    sa.Column('ai_score', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='AI评分（0-10）'),
    sa.Column('is_high_conversion', sa.Integer(), nullable=True, comment='是否高转化话术：1是 0否'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_segments')
    op.drop_table('transcript_full_texts')
    op.drop_index('idx_session_metric_time', table_name='live_metrics')
    op.drop_table('live_metrics')
    op.drop_table('live_audience_profiles')
    op.drop_table('leads')
    op.drop_table('knowledge_base')
    op.drop_table('comments')
    op.drop_table('analysis_reports')
    op.drop_table('live_sessions')
    op.drop_table('live_rooms')
    # ### end Alembic commands ###
