/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'analysis',
    path: '/analysis',
    component: 'layout.base$view.analysis',
    meta: {
      title: 'analysis',
      i18nKey: 'route.analysis',
      icon: 'mdi:chart-bar',
      order: 6,
      keepAlive: true
    }
  },
  {
    name: 'collector',
    path: '/collector',
    component: 'layout.base$view.collector',
    meta: {
      title: 'collector',
      i18nKey: 'route.collector',
      icon: 'mdi:cloud-upload',
      order: 3,
      keepAlive: true
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard',
      icon: 'mdi:view-dashboard-outline',
      order: 2,
      keepAlive: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'knowledge',
    path: '/knowledge',
    component: 'layout.base$view.knowledge',
    meta: {
      title: 'knowledge',
      i18nKey: 'route.knowledge',
      icon: 'mdi:book-open-variant',
      order: 7,
      keepAlive: true
    }
  },
  {
    name: 'live-session-ai-analysis',
    path: '/live-sessions/:id/ai-analysis',
    component: 'layout.base$view.live-session-ai-analysis',
    props: true,
    meta: {
      title: 'live-session-ai-analysis',
      i18nKey: 'route.live-session-ai-analysis',
      hideInMenu: true,
      activeMenu: 'live-sessions',
      multiTab: true
    }
  },
  {
    name: 'live-session-detail',
    path: '/live-sessions/:id',
    component: 'layout.base$view.live-session-detail',
    props: true,
    meta: {
      title: 'live-session-detail',
      i18nKey: 'route.live-session-detail',
      hideInMenu: true,
      activeMenu: 'live-sessions',
      multiTab: true
    }
  },
  {
    name: 'live-sessions',
    path: '/live-sessions',
    component: 'layout.base$view.live-sessions',
    meta: {
      title: 'live-sessions',
      i18nKey: 'route.live-sessions',
      icon: 'mdi:video-vintage',
      order: 4,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'transcripts',
    path: '/transcripts',
    component: 'layout.base$view.transcripts',
    meta: {
      title: 'transcripts',
      i18nKey: 'route.transcripts',
      icon: 'mdi:chat-processing',
      order: 5,
      keepAlive: true
    }
  },
  {
    name: 'user-management',
    path: '/user-management',
    component: 'layout.base$view.user-management',
    meta: {
      title: 'user-management',
      i18nKey: 'route.user-management',
      icon: 'mdi:account-group',
      order: 8,
      keepAlive: true,
      roles: ['R_SUPER']
    }
  }
];
